# Generated by Django 4.0.2 on 2022-06-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_worker_age_alter_worker_exp_alter_worker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название отдела', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='Departament',
        ),
        migrations.AddField(
            model_name='worker',
            name='Departament',
            field=models.ManyToManyField(help_text='Выберете отдел для сотрудника', to='catalog.departament'),
        ),
    ]
