# Generated by Django 4.0.2 on 2022-06-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_departament_remove_worker_departament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='age',
        ),
        migrations.AddField(
            model_name='worker',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
