# Generated by Django 4.0.2 on 2022-06-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_worker_age_worker_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('desc', models.TextField()),
            ],
        ),
    ]
