# Generated by Django 4.0.2 on 2022-06-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_news_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date']},
        ),
    ]
