# Generated by Django 4.0.2 on 2022-07-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='cat.jpeg', upload_to='static/img'),
        ),
    ]
